[package]
name = "tijira"
version = "0.1.0"
authors = ["Scott Hardy <hardy613+tijira@gmail.com>"]

[dependencies]
futures = "0.1"
clap = "2.29.2"
log = "0.4.1"
reqwest = "0.8.4"
serde = "1.0"
serde_json = "1.0"

[[bin]]
name = "tijira"
path = "src/main.rs"
